image: viniro/cypress-bitbucket:1.0

pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - npm install
            - npm run build
            - npm test
            - cd output
            - zip -r deploy.zip .
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: "deploy.zip"


